### ISSUE TITLE
implement archiveSession

### ISSUE THREAD

**Issue by johanvos** [gluonhq/ChatApp#108]
When stale devices need to be handled, we need to invoke archiveSession which is currently not implemented.

Exception in thread "JavaFX Application Thread" java.lang.UnsupportedOperationException: Not supported yet.
        at com.gluonhq.wave@0.9.1/com.gluonhq.wave.WaveStore.archiveSession(WaveStore.java:285)
        at org.whispersystems.service@2.15.4-gluon-6/org.whispersystems.signalservice.api.SignalServiceMessageSender.handleStaleDevices(SignalServiceMessageSender.java:1693)

**Comment by johanvos** [comment]
Implemented in wave 0.9.3
